import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import Link from 'next/link'
import type { Metadata } from 'next'

/* ── ARTICLES DATABASE ───────────────────────────────────────
   Add each article here. The slug must match the /insights page. */
const ARTICLES: Record<string, {
  category: string
  title: string
  date: string
  author: string
  readTime: string
  content: string[]
}> = {
  'epr-compliance-guide-andhra-pradesh-2026': {
    category: 'EPR',
    title: 'The Complete EPR Compliance Guide for Andhra Pradesh Businesses in 2026',
    date: 'May 15, 2026',
    author: 'RevivaGreen Strategy Team',
    readTime: '8 min read',
    content: [
      'Extended Producer Responsibility (EPR) is no longer a future obligation for Indian businesses — it is a present legal requirement with real penalties for non-compliance.',
      'The Environment (Protection) Act and its subsidiary rules now mandate that producers, importers, and brand owners of plastic packaging, electronic equipment, batteries, and tyres take responsibility for the end-of-life management of their products.',
      'For businesses operating in Andhra Pradesh, this means engaging with APPCB-authorised collection and recycling channels — and maintaining documentation that proves you did so.',
      'This guide covers what EPR means for your business, which categories are covered, and the practical steps to achieve compliance in 2026.',
      '## Which businesses are covered?',
      'EPR obligations apply to: producers and importers of plastic packaging materials, electronic and electrical equipment manufacturers and importers, battery manufacturers and importers, and tyre manufacturers and importers.',
      'If your business generates waste in any of these categories — even as a downstream user — you have an obligation to ensure it is channelled to an authorised recycler.',
      '## What documentation do you need?',
      'At minimum, your EPR compliance documentation should include: collection certificates from authorised collection partners, recycling certificates from CPCB-registered recyclers, material weight records by category, and annual compliance filings with the relevant authority.',
      '## How RevivaGreen supports EPR compliance',
      'RevivaGreen is an APPCB-authorised resource recovery partner. We collect your EPR-covered materials, channel them to certified recyclers, and provide you with the documentation you need for your annual filing.',
      'Our EPR compliance service starts from ₹3L per year for managed service clients. Contact us to discuss your specific obligations and volume.',
    ],
  },
  'brsr-waste-data-explainer': {
    category: 'BRSR',
    title: 'How to Complete BRSR Principle 6 — A Practical Guide for Waste Data',
    date: 'May 8, 2026',
    author: 'RevivaGreen Strategy Team',
    readTime: '6 min read',
    content: [
      'SEBI\'s Business Responsibility and Sustainability Report (BRSR) framework requires structured disclosure across nine principles. Principle 6 — Responsible Business in Respect of Environment — is where waste data lives.',
      'For most businesses, Principle 6 is also where their BRSR report is weakest. Without a compliant waste management partner providing structured data, the waste sections are either left blank or filled with estimates.',
      '## What Principle 6 requires',
      'Under Principle 6, Essential Indicator 8 requires disclosure of total waste generated by category, total waste recovered through recycling, reuse, or other recovery operations, and total waste disposed.',
      'The data must be specific to your operations, broken down by material type, and — increasingly — verified by a third party.',
      '## Where most businesses go wrong',
      'The most common failure point is the absence of material-level data from waste vendors. If your scrap dealer cannot tell you exactly how many kilograms of iron, aluminium, copper, and plastic they collected from you last year, you cannot complete Principle 6 accurately.',
      '## How to fix it',
      'Switch to a vendor who provides material-level documentation on every pickup — with weights broken down by category and linked to GST invoice records. RevivaGreen provides this data automatically to all clients through our ESG dashboard.',
      'Your auditor can then independently verify your BRSR Principle 6 data against our GST invoice records — making your sustainability report credible, not just compliant.',
    ],
  },
}

/* ── GENERATE STATIC PARAMS ──────────────────────────────── */
export async function generateStaticParams() {
  return Object.keys(ARTICLES).map((slug) => ({ slug }))
}

/* ── METADATA ────────────────────────────────────────────── */
export async function generateMetadata({
  params,
}: {
  params: Promise<{ slug: string }>
}): Promise<Metadata> {
  const { slug } = await params
  const article = ARTICLES[slug]
  if (!article) return { title: 'Article not found | RevivaGreen Insights' }
  return {
    title: `${article.title} | RevivaGreen Insights`,
    description: article.content[0]?.slice(0, 160),
  }
}

/* ── PAGE ────────────────────────────────────────────────── */
export default async function ArticlePage({
  params,
}: {
  params: Promise<{ slug: string }>
}) {
  const { slug } = await params
  const article = ARTICLES[slug]

  if (!article) {
    return (
      <main>
        <Navbar />
        <div className="min-h-[60vh] flex items-center justify-center">
          <div className="text-center">
            <h1 className="h2 text-[#0A1F14] mb-4">Article not found</h1>
            <Link href="/insights" className="btn-primary">
              Back to Insights
            </Link>
          </div>
        </div>
        <Footer />
      </main>
    )
  }

  const CATEGORY_COLORS: Record<string, string> = {
    'EPR':              'bg-[#E1F5EE] text-[#085041]',
    'BRSR':             'bg-[#EAF0FF] text-[#1A3C8C]',
    'Circular Economy': 'bg-[#FFF8E8] text-[#7A5500]',
    'Company News':     'bg-[#F5F0E8] text-[#5A5850]',
  }

  return (
    <main>
      <Navbar />

      {/* ── ARTICLE HERO ──────────────────────────────────── */}
      <section className="bg-[#F5F0E8] pt-40 pb-16 border-b border-[#D3D1C7]">
        <div className="container">
          <div className="max-w-3xl">
            <Link
              href="/insights"
              className="inline-flex items-center gap-2 text-[#888780] text-[13px] hover:text-[#1D9E75] transition-colors mb-8"
            >
              <svg width="14" height="14" viewBox="0 0 16 16" fill="none" aria-hidden="true">
                <path d="M13 8H3M3 8L7 4M3 8L7 12" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
              </svg>
              Back to Insights
            </Link>

            <span
              className={`inline-block text-[11px] font-semibold uppercase tracking-[0.1em] px-3 py-1.5 rounded-full mb-5 ${CATEGORY_COLORS[article.category] ?? 'bg-[#F5F0E8] text-[#5A5850]'}`}
            >
              {article.category}
            </span>

            <h1 className="h1 text-[#0A1F14] mb-6" style={{ fontSize: 'clamp(28px, 4vw, 48px)' }}>
              {article.title}
            </h1>

            <div className="flex flex-wrap items-center gap-4 text-[14px] text-[#888780]">
              <span className="font-medium text-[#2C2C2A]">{article.author}</span>
              <span className="w-1 h-1 rounded-full bg-[#D3D1C7]" />
              <span>{article.date}</span>
              <span className="w-1 h-1 rounded-full bg-[#D3D1C7]" />
              <span>{article.readTime}</span>
            </div>
          </div>
        </div>
      </section>

      {/* ── ARTICLE CONTENT ───────────────────────────────── */}
      <section className="bg-white section-py">
        <div className="container">
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-16">

            {/* Article body */}
            <article className="lg:col-span-2 prose-revivagreen">
              {article.content.map((block, i) => {
                if (block.startsWith('## ')) {
                  return (
                    <h2
                      key={i}
                      className="text-[#0A1F14] font-medium text-[24px] leading-[1.3] mt-10 mb-4 first:mt-0"
                    >
                      {block.replace('## ', '')}
                    </h2>
                  )
                }
                return (
                  <p
                    key={i}
                    className="text-[#2C2C2A] text-[17px] leading-[1.75] mb-5"
                  >
                    {block}
                  </p>
                )
              })}

              {/* Article CTA */}
              <div className="mt-12 bg-[#F5F0E8] border border-[#1D9E75]/20 rounded-2xl p-8">
                <p className="text-[#1D9E75] text-[11px] font-semibold uppercase tracking-[0.1em] mb-3">
                  Need help with compliance?
                </p>
                <p className="text-[#0A1F14] font-medium text-[18px] mb-3">
                  RevivaGreen handles EPR and BRSR compliance for 100+ AP businesses.
                </p>
                <p className="text-[#888780] text-[15px] mb-5">
                  We provide GST-invoiced collections, structured ESG data, and full
                  compliance documentation — so you can focus on your business.
                </p>
                <Link href="/contact" className="btn-primary">
                  Request a demo →
                </Link>
              </div>
            </article>

            {/* Sidebar */}
            <aside className="space-y-8">

              {/* About the author */}
              <div className="border border-[#D3D1C7] rounded-xl p-5">
                <p className="text-[11px] font-semibold uppercase tracking-[0.1em] text-[#888780] mb-4">
                  About the author
                </p>
                <div className="flex items-center gap-3 mb-3">
                  <div className="w-10 h-10 rounded-full bg-[#1D9E75]/10 border-2 border-[#1D9E75] flex items-center justify-center">
                    <span className="text-[#1D9E75] text-[12px] font-semibold">RG</span>
                  </div>
                  <div>
                    <p className="text-[#0A1F14] font-medium text-[14px]">{article.author}</p>
                    <p className="text-[#888780] text-[12px]">RevivaGreen Ventures</p>
                  </div>
                </div>
                <p className="text-[#888780] text-[13px] leading-[1.65]">
                  Regulatory intelligence and compliance guidance for businesses in Andhra Pradesh.
                </p>
              </div>

              {/* Share */}
              <div className="border border-[#D3D1C7] rounded-xl p-5">
                <p className="text-[11px] font-semibold uppercase tracking-[0.1em] text-[#888780] mb-4">
                  Share this article
                </p>
                <div className="flex gap-3">
                  <a
                    href={`https://www.linkedin.com/sharing/share-offsite/?url=https://revivagreen.com/insights/${slug}`}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="flex-1 flex items-center justify-center gap-2 py-2.5 border border-[#D3D1C7] rounded-lg text-[13px] text-[#888780] hover:border-[#1D9E75] hover:text-[#1D9E75] transition-colors"
                  >
                    LinkedIn
                  </a>
                  <a
                    href={`https://twitter.com/intent/tweet?url=https://revivagreen.com/insights/${slug}&text=${encodeURIComponent(article.title)}`}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="flex-1 flex items-center justify-center gap-2 py-2.5 border border-[#D3D1C7] rounded-lg text-[13px] text-[#888780] hover:border-[#1D9E75] hover:text-[#1D9E75] transition-colors"
                  >
                    X / Twitter
                  </a>
                </div>
              </div>

              {/* More articles */}
              <div className="border border-[#D3D1C7] rounded-xl p-5">
                <p className="text-[11px] font-semibold uppercase tracking-[0.1em] text-[#888780] mb-4">
                  More insights
                </p>
                <Link
                  href="/insights"
                  className="inline-flex items-center gap-2 text-[#1D9E75] text-[14px] font-medium hover:underline"
                >
                  View all articles →
                </Link>
              </div>

            </aside>
          </div>
        </div>
      </section>

      <Footer />
    </main>
  )
}